import Head from "next/head";
import { Footer, Navbar } from ".";

const Layout = ({ children }) => {
  return (
    <div className="layout p-[0] md:p-[10px]">
      <Head>
        <title>EZ Shoes Store</title>
        <meta name="description" content="Generated by EliezerCoding" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className="main-container">
        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export default Layout;